links:
  shellenv.sh: ~/.shellenv
  bash_profile.sh: ~/.bash_profile
  bashrc.sh: ~/.bashrc
  zshrc.sh: ~/.zshrc
  .gitignore: ~/.gitignore
  chunkwmrc.sh: ~/.chunkwmrc
  skhdrc.sh: ~/.skhdrc
  vscode-settings.json: ~/Library/Application Support/Code/User/settings.json
  "../bin/dotapply": /usr/local/bin/dotapply
devtools_config:
  default_node: 10
  global_node_packages:
    - create-react-app
    - pure-prompt
  global_python_packages:
    - virtualenv
    - jupyter
  default_ruby: 2.4.2
  global_ruby_packages:
    - cocoapods
  vscode_extensions:
    - wesbos.theme-cobalt2
    - EditorConfig.editorconfig
    - msjsdiag.debugger-for-chrome
    - flowtype.flow-for-vscode
    - dbaeumer.vscode-eslint
    - esbenp.prettier-vscode