links:
  shellenv.sh: ~/.shellenv
  bash_profile.sh: ~/.bash_profile
  bashrc.sh: ~/.bashrc
  zshrc.sh: ~/.zshrc
  .gitignore: ~/.gitignore
  chunkwmrc.sh: ~/.chunkwmrc
  vscode-settings.json: ~/Library/Application Support/Code/User/settings.json
  "../bin/dotapply": /usr/local/bin/dotapply
devtools_config:
  default_node: 8
  global_node_packages:
    - create-react-app
    - create-react-native-app
    - nodemon
    - pure-prompt
    - serve
    - bs-platform
    - https://github.com/reasonml/reason-cli/archive/beta-v-1.13.7-bin-darwin.tar.gz
  global_python_packages:
    - virtualenv
    - jupyter
  default_ruby: 2.4.2
  global_ruby_packages:
    - cocoapods
  vscode_extensions:
    - zhuangtongfa.material-theme
    - akamud.vscode-theme-onelight
    - EditorConfig.editorconfig
    - msjsdiag.debugger-for-chrome
    - flowtype.flow-for-vscode
    - dbaeumer.vscode-eslint
    - vsmobile.vscode-react-native
    - freebroccolo.reasonml
    - PeterJausovec.vscode-docker